data_btn= {"school":{1:["image/School/17.png","audio/School/17.wav","bag","сумка"],
                2:["image/School/18.png","audio/School/18.wav","board","дошка"],
                3:["image/School/19.png","audio/School/19.wav","notes","замітки"],
                4:["image/School/20.png","audio/School/20.wav","book","книга"],
                5:["image/School/21.png","audio/School/21.wav","bell","дзвінок"],
                6:["image/School/22.png","audio/School/22.wav","magnifier","лупа"],
                7:["image/School/23.png","audio/School/23.wav","hat","шапка"],
                8:["image/School/24.png","audio/School/24.wav","clock","годинник"]},

            "animal":{1:["image/Animals/10.png","audio/Animals/10.wav","panda","панда"],
                2:["image/Animals/14.png","audio/Animals/14.wav","tiger","тигр"],
                3:["image/Animals/11.png","audio/Animals/11.wav","otter","сурикат"],
                4:["image/Animals/13.png","audio/Animals/13.wav","bear","ведмідь"],
                5:["image/Animals/9.png","audio/Animals/9.wav","dog","собака"],
                6:["image/Animals/12.png","audio/Animals/12.wav","octopus","восьминіг"],
                7:["image/Animals/15.png","audio/Animals/15.wav","dinosaur","динозавр"],
                8:["image/Animals/16.png","audio/Animals/16.wav","owl","сова"]},
           
           "car":{1:["image/Transport/1.png","audio/Transport/1.wav","taxi","таксі"],
                  2:["image/Transport/2.png","audio/Transport/2.wav","mixer","змішувач"],
                  3:["image/Transport/3.png","audio/Transport/3.wav","police","поліція"],
                  4:["image/Transport/4.png","audio/Transport/4.wav","bus","автобус"],
                  5:["image/Transport/5.png","audio/Transport/5.wav","lorry","вантажівка"],
                  6:["image/Transport/6.png","audio/Transport/6.wav","car","машина"],
                  7:["image/Transport/8.png","audio/Transport/8.wav","van","фургон"],
                  8:["image/Transport/7.png","audio/Transport/7.wav","helicopter","гвинтокрил"]},

            "items":{1:["image/Items/24.png","audio/Items/24.wav","microwave","микрохвильовка"],
                2:["image/Items/25.png","audio/Items/25.wav","laundry","пралка"],
                3:["image/Items/26.png","audio/Items/26/wav","oven","піч"],
                4:["image/Items/27.png","audio/Items/27.wav","refrigerator","холодильник"],
                5:["image/Items/29.png","audio/Items/29.wav","kettle","чайник"],
                6:["image/Items/30.png","audio/Items/30.wav","iron","утюг"],
                7:["image/Items/31.png","audio/Items/31.wav","toaster","тостер"],
                8:["image/Items/32.png","audio/Items/32.wav","mixer","миксер"]}
}